In [1]:
import numpy as np

In [7]:
rows = int(input("Enter number of rows:"))
columns = int(input("Enter number of columns:"))

print("Enter elements of first matrix:")
A = np.array([[int(input())for j in range(columns)]for i in range(rows)])

print("Enter elements of second matrix:")
B  = np.array([[int(input())for j in range(columns)]for i in range(rows)])

C = A + B

print("First Matrix:")
print(A)

print("Second Matrix:")
print(B)

print("Sum of two matrices:")
print(C)


Enter number of rows: 2
Enter number of columns: 2


Enter elements of first matrix:


 1
 2
 3
 4


Enter elements of second matrix:


 5
 6
 7
 8


First Matrix:
[[1 2]
 [3 4]]
Second Matrix:
[[5 6]
 [7 8]]
Sum of two matrices:
[[ 6  8]
 [10 12]]
